# Generated by Django 4.2.3 on 2023-08-21 18:10

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personne', '0001_initial'),
        ('TypeDeService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employé',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('carteIdentite', models.CharField(max_length=20)),
                ('addresse', models.CharField(max_length=200)),
                ('typedeservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TypeDeService.typedeservice')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Personne.personne',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
