# Generated by Django 4.2.3 on 2023-08-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
